# Generated by Django 2.2.5 on 2019-10-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_handle', models.CharField(max_length=30, verbose_name='Account handle')),
                ('cat', models.BooleanField(default=False)),
                ('dog', models.BooleanField(default=False)),
            ],
        ),
    ]
